---
- name: Aktualizacja Systemu 
  hosts: linux
  become: yes

  tasks:
    - name: 1. Aktualizacja pamięci podręcznej 
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: 2. Aktualizacja pakietów 
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: 3. Czy wymagany jest restart serwera
      stat:
        path: /var/run/reboot-required
      register: reboot_file

    - name: 4. Wyświetl informację o konieczności restartu
      debug:
        msg: "Serwer wymaga restartu po aktualizacji"
      when: reboot_file.stat.exists